
PATH=`pwd`/bin:$PATH
export FABRIC_CFG_PATH=.
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_TLS_CERT_FILE=./tls/client.crt
export CORE_PEER_TLS_KEY_FILE=./tls/client.key
export CORE_PEER_MSPCONFIGPATH=./msp
export CORE_PEER_ADDRESS=${PEER}.${ORG}.${DOMAIN}:${REQUEST_PORT}
export CORE_PEER_LOCALMSPID=${ORGMSP}
export CORE_PEER_TLS_ROOTCERT_FILE=./tls/ca.crt
export CORE_PEER_ID=${PEER}.${ORG}.${DOMAIN}
export CORE_LOGGING_LEVEL=${LOGGING_LEVEL}
peer \$*