version: '2'
services:
  zookeeper:
    image: reg-mirror.shie.site/library/wurstmeister/zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
  kafka1:
    image: reg-mirror.shie.site/library/wurstmeister/kafka:1.1.0
    ports:
      - "${KAFKA1_PORT}:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA1_HOST}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: reg-mirror.shie.site/library/wurstmeister/kafka:1.1.0
    ports:
      - "${KAFKA2_PORT}:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA2_HOST}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: reg-mirror.shie.site/library/wurstmeister/kafka:1.1.0
    ports:
      - "${KAFKA3_PORT}:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA3_HOST}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock